---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull-secret
  namespace: authorworks
spec:
  encryptedData:
    .dockerconfigjson: AgA/ZwEMiXxetHtlTJWqJ2FHmbfCv2hlpPTjx5u7GOptVrLXFqMQECyNzrCLUzFD7/zdwF0Gys4O57b8tEHt8OhXHI+VhjRpPjtShkxvbL2rjoy7hnLGSyAiwaS4/H2FHlGtsC9F4J0yYlFh3huc1SC2w2GBPH0VDTaeZTWtG1iZNPJMzfsYQ8caJLDTMSgEcBxXUpZrriRrQ6J0NwJYwtTDJfC+hkUJhA+mZjfmpDxziv8SNhwXod0lvFdrf9l+J2bVVjN3NurgyY8pRieAEBWMMlWBGL1nttEPRkR0RVJ/hRghh1L+IgRv2HDehb4Ineddv3YVfIkKrpV1pPXoePXmyOcvQG6m+ZkCYRhXMEZR9kl7pAkZud6Z7C+37gfGpRsyLza0GVUO2V5OHDq6i84waW/Esn9ft5E9vqDg+x6AO/BvHraLeIm9723HojPAlYHJPpqmJKjtNCbpUNN+iMBpM8LxIisPVYVBHVckOnA50nCargenv/FgL6pFwGvFXtvulCMr5W6TJuBKtgFVVqjr9LxKnb3IFL1FVK3Q/FIUM1IS+G+C2yNs7SDJknDQqH8RnVWtXG1Y8DmhLe5Dic6PINcUw93gFKHocGx8OSS/x/ckPS01A/2Omz+ZXM92yp4pkbS6gTLL2e3VR/8pqmPCGj0o9tbE36Qr1R3VbgfIM76MVb4BZlO4EEaKamVsNa1c18S2EvUFe6ZhLhSQN6aAypP4kTPohYcu28nIq2pNt3VsSEQbBc7rNr8fEM3QrH+d4fXhSCTEVBF9Ulkq+08cg9s3ieT9mho7V38zstmkg6L6fmEPu3nFrrxSto6ksAAnO6p5j+2MEh3VxtEiRus2IAjR9BHmo1vjGSLrHlQtIMNyoW1s8xPRGpJ2tWcZ2lUObNE9K9U2LSlHBZJFJ1chbnwbk14/ztkV1rDgKXQ70vqAkr88Ed4RpYob4mfEmQ==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-pull-secret
      namespace: authorworks
    type: kubernetes.io/dockerconfigjson
