apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authorworks

resources:
- ../../base-minimal
- simple-deployment.yaml
- sealed-secrets.yaml
- ghcr-sealed-secret.yaml
- content-worker.yaml

labels:
- pairs:
    environment: homelab

images:
- name: ghcr.io/authorworks/authorworks-platform
  newTag: homelab
- name: ghcr.io/authorworks/frontend
  newTag: homelab

replicas:
- name: authorworks-server
  count: 1
