apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authorworks

resources:
- ../../base

# Note: SpinApp replicas managed in base spinapp.yaml

labels:
- pairs:
    environment: homelab

images:
- name: ghcr.io/authorworks/authorworks-platform
  newTag: latest
