apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: spin-operator
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webhook-server-cert
  namespace: spin-operator
spec:
  secretName: webhook-server-cert
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - spinkube
  dnsNames:
    - spin-operator-webhook-service.spin-operator.svc
    - spin-operator-webhook-service.spin-operator.svc.cluster.local
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
